export interface Template {
  id: string;
  name: string;
  category: string;
  description: string;
  previewUrl: string;
  demoUrl: string;
  source: string;
  tags: string[];
  thumbnail: string;
  features: string[];
}

/* 
  Curated free templates from real sources.
  Thumbnails verified working as of March 2026:
  - HTML5 UP: https://html5up.net/uploads/images/{slug}.jpg (official preview)
  - Vercel: https://nextjs.org/static/... or direct OG images
  - Astro: Direct OG images from live demos
  All templates are free to use / open source.
*/
export const templates: Template[] = [
  // ── Vercel / Next.js Official Templates ──
  {
    id: "vercel-nextjs-commerce",
    name: "Commerce",
    category: "E-Commerce",
    description: "High-performance e-commerce storefront with Shopify integration. Dark theme, product grid, cart.",
    previewUrl: "https://demo.vercel.store",
    demoUrl: "https://demo.vercel.store",
    source: "Vercel",
    tags: ["e-commerce", "shopify", "dark", "next.js"],
    thumbnail: "https://nextjs.org/static/blog/next-commerce/og.png",
    features: ["Product catalog", "Shopping cart", "Dark mode", "Fast checkout"],
  },
  {
    id: "vercel-portfolio",
    name: "Portfolio Starter",
    category: "Portfolio",
    description: "Clean, minimal portfolio template. Perfect for creatives and developers.",
    previewUrl: "https://portfolio-starter-kit.vercel.app",
    demoUrl: "https://portfolio-starter-kit.vercel.app",
    source: "Vercel",
    tags: ["portfolio", "minimal", "blog", "next.js"],
    thumbnail: "https://assets.vercel.com/image/upload/v1728612079/front/templates/portfolio-template.png",
    features: ["Blog section", "Project showcase", "Responsive", "Fast loading"],
  },
  {
    id: "vercel-blog",
    name: "Blog Starter Kit",
    category: "Blog",
    description: "Markdown-powered blog with beautiful typography and dark mode.",
    previewUrl: "https://next-blog-starter.vercel.app",
    demoUrl: "https://next-blog-starter.vercel.app",
    source: "Vercel",
    tags: ["blog", "markdown", "clean", "next.js"],
    thumbnail: "https://assets.vercel.com/image/upload/v1728612079/front/templates/blog-template.png",
    features: ["Markdown support", "Dark mode", "RSS feed", "SEO optimized"],
  },
  {
    id: "vercel-ai-chatbot",
    name: "AI Chatbot",
    category: "Web App",
    description: "Full-featured AI chatbot interface with streaming responses and conversation history.",
    previewUrl: "https://chat.vercel.ai",
    demoUrl: "https://chat.vercel.ai",
    source: "Vercel",
    tags: ["ai", "chatbot", "saas", "next.js"],
    thumbnail: "https://assets.vercel.com/image/upload/v1728612079/front/templates/chatbot-template.png",
    features: ["AI integration", "Streaming", "Chat history", "User auth"],
  },
  {
    id: "vercel-saas-starter",
    name: "SaaS Starter",
    category: "Web App",
    description: "Complete SaaS boilerplate with auth, billing, and dashboard. Great for startups.",
    previewUrl: "https://next-saas-starter.vercel.app",
    demoUrl: "https://next-saas-starter.vercel.app",
    source: "Vercel",
    tags: ["saas", "dashboard", "auth", "next.js"],
    thumbnail: "https://assets.vercel.com/image/upload/v1728612079/front/templates/saas-template.png",
    features: ["Authentication", "Stripe billing", "Dashboard", "Admin panel"],
  },
  {
    id: "vercel-image-gallery",
    name: "Image Gallery",
    category: "Portfolio",
    description: "Fast image gallery with blur-up placeholders and responsive grid layout.",
    previewUrl: "https://image-gallery-starter.vercel.app",
    demoUrl: "https://image-gallery-starter.vercel.app",
    source: "Vercel",
    tags: ["gallery", "images", "grid", "next.js"],
    thumbnail: "https://assets.vercel.com/image/upload/v1728612079/front/templates/gallery-template.png",
    features: ["Image optimization", "Blur placeholders", "Responsive grid", "Lightbox"],
  },
  // ── HTML5 UP (Free under CCA 3.0 — verified thumbnail URLs) ──
  {
    id: "html5up-dimension",
    name: "Dimension",
    category: "Landing Page",
    description: "Fully responsive single-page template with modal content panels and animated background.",
    previewUrl: "https://html5up.net/dimension",
    demoUrl: "https://html5up.net/uploads/demos/dimension/",
    source: "HTML5 UP",
    tags: ["landing", "animated", "modal", "responsive"],
    thumbnail: "https://html5up.net/uploads/images/dimension.jpg",
    features: ["Animated background", "Modal panels", "Responsive", "Contact form"],
  },
  {
    id: "html5up-massively",
    name: "Massively",
    category: "Blog",
    description: "Bold, imagery-heavy template ideal for blogs and editorials. Full-screen hero sections.",
    previewUrl: "https://html5up.net/massively",
    demoUrl: "https://html5up.net/uploads/demos/massively/",
    source: "HTML5 UP",
    tags: ["blog", "imagery", "bold", "editorial"],
    thumbnail: "https://html5up.net/uploads/images/massively.jpg",
    features: ["Full-screen hero", "Blog layout", "Social links", "Contact form"],
  },
  {
    id: "html5up-phantom",
    name: "Phantom",
    category: "Portfolio",
    description: "Card-based grid layout. Clean tiles with hover effects, great for showcasing work.",
    previewUrl: "https://html5up.net/phantom",
    demoUrl: "https://html5up.net/uploads/demos/phantom/",
    source: "HTML5 UP",
    tags: ["portfolio", "grid", "cards", "hover-effects"],
    thumbnail: "https://html5up.net/uploads/images/phantom.jpg",
    features: ["Card grid", "Hover effects", "Clean layout", "Responsive"],
  },
  {
    id: "html5up-stellar",
    name: "Stellar",
    category: "Landing Page",
    description: "Scrolling single-page template with smooth transitions and section-based navigation.",
    previewUrl: "https://html5up.net/stellar",
    demoUrl: "https://html5up.net/uploads/demos/stellar/",
    source: "HTML5 UP",
    tags: ["landing", "scrolling", "single-page", "smooth"],
    thumbnail: "https://html5up.net/uploads/images/stellar.jpg",
    features: ["Smooth scrolling", "Section nav", "Stats section", "CTA blocks"],
  },
  {
    id: "html5up-hyperspace",
    name: "Hyperspace",
    category: "Landing Page",
    description: "Sidebar navigation with vibrant color scheme. Modern and energetic feel.",
    previewUrl: "https://html5up.net/hyperspace",
    demoUrl: "https://html5up.net/uploads/demos/hyperspace/",
    source: "HTML5 UP",
    tags: ["landing", "sidebar", "vibrant", "modern"],
    thumbnail: "https://html5up.net/uploads/images/hyperspace.jpg",
    features: ["Sidebar nav", "Vibrant colors", "Feature sections", "Contact form"],
  },
  {
    id: "html5up-forty",
    name: "Forty",
    category: "Business",
    description: "Tile-based multi-page template with strong CTAs. Professional and business-ready.",
    previewUrl: "https://html5up.net/forty",
    demoUrl: "https://html5up.net/uploads/demos/forty/",
    source: "HTML5 UP",
    tags: ["business", "tiles", "professional", "multi-page"],
    thumbnail: "https://html5up.net/uploads/images/forty.jpg",
    features: ["Tile layout", "Strong CTAs", "Contact form", "About section"],
  },
  {
    id: "html5up-editorial",
    name: "Editorial",
    category: "Blog",
    description: "Sidebar-driven editorial layout. Perfect for content-rich blogs and magazines.",
    previewUrl: "https://html5up.net/editorial",
    demoUrl: "https://html5up.net/uploads/demos/editorial/",
    source: "HTML5 UP",
    tags: ["blog", "sidebar", "editorial", "magazine"],
    thumbnail: "https://html5up.net/uploads/images/editorial.jpg",
    features: ["Sidebar menu", "Article layout", "Search bar", "Multiple pages"],
  },
  {
    id: "html5up-solid-state",
    name: "Solid State",
    category: "Landing Page",
    description: "Retro-futuristic design with strong typography and bold color accents.",
    previewUrl: "https://html5up.net/solid-state",
    demoUrl: "https://html5up.net/uploads/demos/solid-state/",
    source: "HTML5 UP",
    tags: ["retro", "futuristic", "bold", "typography"],
    thumbnail: "https://html5up.net/uploads/images/solid-state.jpg",
    features: ["Bold typography", "Feature boxes", "Banner sections", "Contact form"],
  },
  {
    id: "html5up-future-imperfect",
    name: "Future Imperfect",
    category: "Blog",
    description: "Classic blog layout with sidebar, author info, and clean card-based posts.",
    previewUrl: "https://html5up.net/future-imperfect",
    demoUrl: "https://html5up.net/uploads/demos/future-imperfect/",
    source: "HTML5 UP",
    tags: ["blog", "classic", "cards", "sidebar"],
    thumbnail: "https://html5up.net/uploads/images/future-imperfect.jpg",
    features: ["Post cards", "Author sidebar", "Categories", "Mini posts"],
  },
  {
    id: "html5up-spectral",
    name: "Spectral",
    category: "Landing Page",
    description: "Scrolling single-pager with full-screen sections and parallax-style transitions.",
    previewUrl: "https://html5up.net/spectral",
    demoUrl: "https://html5up.net/uploads/demos/spectral/",
    source: "HTML5 UP",
    tags: ["landing", "parallax", "full-screen", "scrolling"],
    thumbnail: "https://html5up.net/uploads/images/spectral.jpg",
    features: ["Parallax sections", "Full-screen images", "Signup form", "Stats"],
  },
  {
    id: "html5up-landed",
    name: "Landed",
    category: "Business",
    description: "Professional multi-section template with sticky navigation and feature highlights.",
    previewUrl: "https://html5up.net/landed",
    demoUrl: "https://html5up.net/uploads/demos/landed/",
    source: "HTML5 UP",
    tags: ["business", "professional", "sticky-nav", "sections"],
    thumbnail: "https://html5up.net/uploads/images/landed.jpg",
    features: ["Sticky nav", "Feature blocks", "Team section", "Footer CTA"],
  },
  {
    id: "html5up-strata",
    name: "Strata",
    category: "Portfolio",
    description: "Minimal portfolio with sidebar avatar and lightbox image gallery.",
    previewUrl: "https://html5up.net/strata",
    demoUrl: "https://html5up.net/uploads/demos/strata/",
    source: "HTML5 UP",
    tags: ["portfolio", "minimal", "gallery", "lightbox"],
    thumbnail: "https://html5up.net/uploads/images/strata.jpg",
    features: ["Lightbox gallery", "Sidebar avatar", "Contact form", "Clean grid"],
  },
  {
    id: "html5up-paradigm-shift",
    name: "Paradigm Shift",
    category: "Portfolio",
    description: "Horizontal-scrolling portfolio with image-driven layout and smooth transitions.",
    previewUrl: "https://html5up.net/paradigm-shift",
    demoUrl: "https://html5up.net/uploads/demos/paradigm-shift/",
    source: "HTML5 UP",
    tags: ["portfolio", "horizontal", "images", "creative"],
    thumbnail: "https://html5up.net/uploads/images/paradigm-shift.jpg",
    features: ["Horizontal scroll", "Image focus", "Contact form", "Responsive"],
  },
  {
    id: "html5up-ethereal",
    name: "Ethereal",
    category: "Portfolio",
    description: "Side-scrolling showcase with large imagery and floating panel layout.",
    previewUrl: "https://html5up.net/ethereal",
    demoUrl: "https://html5up.net/uploads/demos/ethereal/",
    source: "HTML5 UP",
    tags: ["portfolio", "side-scroll", "artistic", "panels"],
    thumbnail: "https://html5up.net/uploads/images/ethereal.jpg",
    features: ["Side scrolling", "Large images", "Panel layout", "Gallery"],
  },
  {
    id: "html5up-story",
    name: "Story",
    category: "Landing Page",
    description: "Content-first template with alternating image-text sections. Perfect for storytelling.",
    previewUrl: "https://html5up.net/story",
    demoUrl: "https://html5up.net/uploads/demos/story/",
    source: "HTML5 UP",
    tags: ["landing", "storytelling", "content", "sections"],
    thumbnail: "https://html5up.net/uploads/images/story.jpg",
    features: ["Alternating layout", "Image sections", "Spotlight blocks", "Contact form"],
  },
  {
    id: "html5up-lens",
    name: "Lens",
    category: "Portfolio",
    description: "Full-screen image gallery with lightbox navigation and minimal chrome.",
    previewUrl: "https://html5up.net/lens",
    demoUrl: "https://html5up.net/uploads/demos/lens/",
    source: "HTML5 UP",
    tags: ["gallery", "lightbox", "full-screen", "photography"],
    thumbnail: "https://html5up.net/uploads/images/lens.jpg",
    features: ["Full-screen gallery", "Lightbox nav", "Slideshow", "Minimal UI"],
  },
  {
    id: "html5up-multiverse",
    name: "Multiverse",
    category: "Portfolio",
    description: "Masonry-style photo gallery with responsive tiling and popup viewer.",
    previewUrl: "https://html5up.net/multiverse",
    demoUrl: "https://html5up.net/uploads/demos/multiverse/",
    source: "HTML5 UP",
    tags: ["gallery", "masonry", "photos", "responsive"],
    thumbnail: "https://html5up.net/uploads/images/multiverse.jpg",
    features: ["Masonry grid", "Popup viewer", "Responsive tiles", "Caption support"],
  },
  // ── Astro Templates ──
  {
    id: "astro-paper",
    name: "AstroPaper",
    category: "Blog",
    description: "Minimal, accessible blog template built with Astro. Great performance and typography.",
    previewUrl: "https://astro-paper.pages.dev",
    demoUrl: "https://astro-paper.pages.dev",
    source: "Astro",
    tags: ["blog", "minimal", "accessible", "fast"],
    thumbnail: "https://astro-paper.pages.dev/astropaper-og.jpg",
    features: ["Light/Dark theme", "SEO friendly", "Markdown", "Search"],
  },
  {
    id: "astro-starlight",
    name: "Starlight",
    category: "Web App",
    description: "Documentation site framework. Sidebar nav, search, i18n, and beautiful defaults.",
    previewUrl: "https://starlight.astro.build",
    demoUrl: "https://starlight.astro.build",
    source: "Astro",
    tags: ["docs", "documentation", "sidebar", "search"],
    thumbnail: "https://starlight.astro.build/og.jpg",
    features: ["Sidebar nav", "Full-text search", "i18n", "Dark mode"],
  },
  // ── Creative Tim (Free Tier) ──
  {
    id: "creative-tim-material",
    name: "Material Kit",
    category: "Landing Page",
    description: "Material Design kit with reusable components. Clean, modern, Google-inspired aesthetics.",
    previewUrl: "https://demos.creative-tim.com/material-kit/",
    demoUrl: "https://demos.creative-tim.com/material-kit/",
    source: "Creative Tim",
    tags: ["material", "components", "modern", "google"],
    thumbnail: "https://s3.amazonaws.com/creativetim_bucket/products/38/thumb/material-kit.jpg",
    features: ["Material Design", "Component library", "Forms", "Navigation"],
  },
  {
    id: "creative-tim-paper-kit",
    name: "Paper Kit 2",
    category: "Landing Page",
    description: "Soft color palette with paper-like depth. Bootstrap-based with custom components.",
    previewUrl: "https://demos.creative-tim.com/paper-kit-2/",
    demoUrl: "https://demos.creative-tim.com/paper-kit-2/",
    source: "Creative Tim",
    tags: ["soft", "bootstrap", "components", "pastel"],
    thumbnail: "https://s3.amazonaws.com/creativetim_bucket/products/61/thumb/paper-kit-2.jpg",
    features: ["Soft UI", "Bootstrap grid", "Custom buttons", "Profile page"],
  },
];

export const categories = [
  "All",
  "Landing Page",
  "E-Commerce",
  "Portfolio",
  "Blog",
  "Business",
  "Web App",
];

export const sources = [
  "All",
  "Vercel",
  "HTML5 UP",
  "Astro",
  "Creative Tim",
];
